#!/usr/bin/env bash

case "$1" in
'TokyoNight')     gtk="Tokyo-Night";;
'OceanicNext')    gtk="Oceanic-Next";;
'Monokai')        gtk="Monokai";;
'Nord')           gtk="Nord";;
'SolarizedDark')  gtk="Solarized-Dark";;
'SolarizedLight') gtk="Numix-Solarized-Light";;
esac

echo "$gtk"
