#!/usr/bin/env bash

case "$1" in
'TokyoNight')     icon="simple-sun";;
'OceanicNext')    icon="simple-doder";;
'Monokai')        icon="simple";;
'Nord')           icon="simple-ruby";;
'SolarizedDark')  icon="solarized-deluxe-iconpack";;
'SolarizedLight') icon="solarized-deluxe-iconpack";;
esac

echo "$icon"
