#!/usr/bin/env bash

case "$1" in
'TokyoNight')     icon="einfach-sun";;
'OceanicNext')    icon="einfach-doder";;
'Monokai')        icon="einfach";;
'Nord')           icon="einfach-ruby";;
'SolarizedDark')  icon="solarized-deluxe-iconpack";;
'SolarizedLight') icon="solarized-deluxe-iconpack";;
esac

echo "$icon"
