#!/usr/bin/env bash

#Variables
DMENU="dmenu -i -l 20 -p"
DMTERM="alacritty -e"
DMEDITOR="${DMTERM} nvim"
DMBROWSER="brave"

# Notes dir
notes="${HOME}/.config/dmscripts/notes"

# Config Files
declare -Ag confedit_list
confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.toml"
confedit_list[bashrc]="$HOME/.bashrc"
confedit_list[fish]="$HOME/.config/fish/config.fish"
confedit_list[neovim]="$HOME/.config/nvim/init.lua"
confedit_list[neovim hlts]="$HOME/.config/nvim/lua/jimno/highlights.lua"
confedit_list[neovim plg]="$HOME/.config/nvim/lua/jimno/plugins.lua"
confedit_list[neovim base]="$HOME/.config/nvim/lua/jimno/base.lua"
confedit_list[neovim maps]="$HOME/.config/nvim/lua/jimno/maps.lua"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[xmobar]="$HOME/.config/xmobar/solarized-dark-xmobar.hs"
confedit_list[xmonad]="$HOME/.config/xmonad/xmonad.hs"
confedit_list[dmscript]="$HOME/.config/dmscripts/config/config"

# Radio Stations
declare -Ag radio_stations 
radio_stations[Quran Station]="https://my.radioalgerie.dz/player/coran.html"
radio_stations[Lofi]="http://192.95.39.65:5607"
radio_stations[J-Pop Kawaii]="https://kathy.torontocast.com:3060"
radio_stations[Mixx Martinique]="http://srv2.streaming-ingenierie.fr:8110"
radio_stations[Jil Fm]="https://my.radioalgerie.dz/player/jilfm.html"
radio_stations[Bah-dja]="https://my.radioalgerie.dz/player/bahdja.html"
radio_stations[Chaine-3]="https://my.radioalgerie.dz/player/chaine3.html"
radio_stations[kill]="nil"

# Web search
declare -Ag websearch 
websearch[Google]="https://www.google.com/search?q="
websearch[Wikipedia]="https://en.wikipedia.org/w/index.php?search="
websearch[Youtube]="https://www.youtube.com/results?search_query="
websearch[AUR]="https://aur.archlinux.org/packages/?0=0&K="
websearch[Archpkg]="https://archlinux.org/packages/?sort=&q="
websearch[ArchWiki]="https://wiki.archlinux.org/index.php?search="
websearch[Gamivo]="https://www.gamivo.com/search/"
websearch[StackOverFlow]="https://www.stackoverflow.com/search?q="
websearch[ThePirateBay]="https://www.thepiratebay.org/search.php?q="
websearch[Hoogle(Haskell)]="https://hoogle.haskell.org/?hoogle="


declare -Ag color_scheme
color_scheme[Monokai]="monokai"
color_scheme[Nord]="nord"
color_scheme[SolarizedDark]="solarized-dark"
color_scheme[SolarizedLight]="solarized-light"
color_scheme[OceanicNext]="oceanic-next"
color_scheme[TokyoNight]="tokyo-night"

declare -Ag font_size
font_size[Comic Mono]="12 10"
font_size[Fira Code]="11 9"
font_size[Cascadia Code]="11 9.5"
font_size[Hack]="11 9.5"
font_size[Inconsolata]="13 10"
font_size[Ubuntu Mono]="12 11"
font_size[Terminus]="13 12"
font_size[Monofur]="12.5 11.5"

# Bookmarks from Brave
declare -Ag bookmarks
while IFS='=' read -r name url; do
    [[ -z "$name" ]] && continue
    bookmarks["$name"]=$url
done < <(cat $HOME/.config/BraveSoftware/Brave-Browser/Default/Bookmarks | grep -E '"name":|"url":' | awk '{
    if ($0 ~ /"name":/) {
        gsub(/[[:space:]]*"name":[[:space:]]*|"[,}]*/, "", $0);
        name = $0;
    } else if ($0 ~ /"url":/) {
        gsub(/[[:space:]]*"url":[[:space:]]*|"[,}]*/, "", $0);
        printf "%s=\"%s\"\n", name, $0;
    }
}' | sed 's/"//g')


# Podcast Rss
declare -Ag rss 
rss[Mach es einfach - Ben Ouattara]="https://feeds.buzzsprout.com/2451303.rss"
rss[Quran - Abdul Basit]="https://anchor.fm/s/f96627a0/podcast/rss"
rss[kill]="nil"
