#!/usr/bin/env bash
set -euo pipefail
source .config/dmscripts/config/config


choice=$(printf 'Copy note\nNew note\nDelete note\nQuit' | ${DMENU} 'Notes:' )


case "$choice" in
'Copy note')
    note_pick=$(${DMENU} 'Copy:' <"${notes}")
    [ -n "${note_pick}" ] && echo "${note_pick}" |  tr -d '\n' | xclip -sel clip && notify-send -u normal "Note copied" "${note_pick}"
    ;;
'New note')
    note_new=$(echo "" | ${DMENU} 'Enter new note:')
    # Making sure the input is not empty and not already exist in notes.
    # The sed command should prevent grep from taking certain characters as a regex input.
    [ -n "$note_new" ] && ! grep -q "^$(echo "${note_new}" | sed -e 's/\[/\\[/g;s/\]/\\]/g')\$" "${notes}" \
    && echo "${note_new}" >>"${notes}" && notify-send -u normal "Note created" "${note_new}"
    ;;
'Delete note')
    note_del=$(${DMENU} 'Delete:' <"${notes}")
    # grep should always returns 0 regardless what happens.
    grep -v "^$(echo "${note_del}" | sed -e 's/\[/\\[/g;s/\]/\\]/g')\$" "${notes}" >"/tmp/dmnote" || true
    [ -n "${note_del}" ] && cp -f "/tmp/dmnote" "${notes}" && notify-send -u normal "Note deleted" "${note_del}"
    ;;
'Quit')
        echo "Program Terminated." && exit 0
    ;;
esac
