#!/usr/bin/env bash

set -euo pipefail
source .config/dmscripts/config/config

# choose a podcast from the list
choice=$(printf '%s\n' "${!rss[@]}" | sort | ${DMENU} 'Listen to:' "$@")

if [ "$choice" = "kill" ]; then
    pkill -f http && exit 0
elif [ "$choice" ]; then
    declare -Ag podcast

    # filter title and url from rss/xml
    output=$(curl -s "${rss["${choice}"]}" | sed -n '/<item>/,/<\/item>/ {s|.*<title>\(.*\)</title>.*|\1|p; s|.*url="\([^"]*\)".*|\1|p}' | paste -d= - -)
    while IFS='=' read -r title url; do
        podcast["$title"]=$url
    done < <(echo "$output")

    # choose an episode
    episode=$(printf '%s\n' "${!podcast[@]}" | sort | ${DMENU} 'Episodes:' "$@")

    if [ "$episode" = "kill" ]; then
        pkill -f http && exit 0 
    elif [ "$episode" ]; then
        pkill -f http || echo "mpv wasn't running." 
        url="${podcast["${episode}"]}"
        mpv --volume=100 --audio-channels=stereo "$url"
    else
        echo "Program terminated." && exit 0
    fi
else 
    echo "Program terminated." && exit 0
fi
