#!/usr/bin/env bash
set -euo pipefail
source $HOME/.config/dmscripts/config/config


logout() {
    pkill xmonad || echo "Cannot kill Xmonad"
}

choice=$(printf 'Suspend\nLog out\nReboot\nPower off' | ${DMENU} 'Power:' "$@")
if [ "$choice" ]; then
    case "${choice}" in
        'Suspend')
            ./.local/bin/stay sudo systemctl suspend
        ;;
        'Log out')
            logout
        ;;
        'Power off')
            ./.local/bin/stay sudo systemctl poweroff
        ;;
        'Reboot')
            ./.local/bin/stay sudo systemctl reboot 
        ;;
    esac
else
    echo "Program terminated." && exit 0
fi
