#!/usr/bin/env bash

set -euo pipefail
source .config/dmscripts/config/config


choice=$(printf '%s\n' "${!radio_stations[@]}" | sort | ${DMENU} 'Listen to:' "$@")

if [ "$choice" = "kill" ]; then
    pkill -f http && exit 0 
elif [ "$choice" ]; then
    pkill -f http || echo "mpv wasn't running." 
    url=$(printf '%s\n' "${radio_stations["${choice}"]}")
    mpv --volume=100 "$url"
else
    echo "Program terminated." && exit 0
fi
