#!/usr/bin/env bash
set -euo pipefail
source $HOME/.config/dmscripts/config/config


# Choose card
card=$(pactl list cards short | awk '{print $2}' | ${DMENU} 'Choose a card:' )


if [ "$card" ]; then
    # Choose output
    output=$(pactl list cards | sed -n "/Name: $card/,/Active Profile:/p" | grep -oP '^\s*output:[^+:]+' | awk '{print $1}' | ${DMENU} 'Choose an output:' )
    
    # Set card profile
    pactl set-card-profile "$card" "$output"
    
    # Set sink
    sink=$(pactl list sinks short | awk '{print $2}' | ${DMENU} 'Choose sink:' )
    if [ "$sink" ]; then
        for i in $(pactl list short sink-inputs | awk '{print $1}'); do pactl move-sink-input "$i" "$sink"; done
    else
        echo "No matching sink found for: $sink" && exit 0
    fi

else
    echo "$card or $output not set properly" && exit 0
fi
