#!/usr/bin/env bash
set -euo pipefail
source .config/dmscripts/config/config

# Drives to ignore (seperated with |)
IGNORED="sda|nvme"
 

mount_usb() {
DEVICE=$(lsblk -lp | grep "part" | grep -Ev "$IGNORED" | sort | ${DMENU} 'Choose drive to mount:' | awk '{print $1}')
# Check if drive is LUKS encrypted
if lsblk -f "$DEVICE" | grep -q "crypto_LUKS"; then
    alacritty -e bash -c "udisksctl unlock -b '$DEVICE'; read -n1 -rsp 'Press any key to close...'"
    MAPPER=$(ls /dev/dm-* | sort | ${DMENU} 'Choose MAPPER:')
    udisksctl mount -b "$MAPPER"
    dunstify -i $HOME/.icons/notif/drive.svg "Drive decrypted and mounted!" "$DEVICE"
else
    udisksctl mount -b "$DEVICE"
    dunstify -i $HOME/.icons/notif/drive.svg "Drive mounted!" "$DEVICE"
fi
}

unmount_usb() {
DEVICE=$(lsblk -lp | grep "part" | grep -Ev "$IGNORED" | sort | ${DMENU} 'Choose drive to unmount:' | awk '{print $1}')
# Check if drive is LUKS encrypted
if lsblk -f "$DEVICE" | grep -q "crypto_LUKS"; then
    MAPPER=$(ls /dev/dm-* | sort | ${DMENU} 'Choose MAPPER:')
    udisksctl unmount -b "$MAPPER"
    udisksctl lock -b "$DEVICE"
    dunstify -i $HOME/.icons/notif/drive.svg "Drive unmounted and crypted!" "$DEVICE"
else
    udisksctl unmount -b "$DEVICE"
    dunstify -i $HOME/.icons/notif/drive.svg "Drive unmounted!" "$DEVICE"
fi
}

choice=$(printf 'Mount USB\nUnmount USB\nMount Phone\nUnmount Phone\nQuit' | ${DMENU} 'USB:')
case "$choice" in
'Mount USB')
    mount_usb
;;
'Unmount USB')
    unmount_usb
;;
'Mount Phone')
    mkdir -p ~/phone
    jmtpfs ~/phone
    dunstify -i $HOME/.icons/notif/phone.svg "Phone mounted!" "~/phone"
;;
'Unmount Phone')
    fusermount -u ~/phone
    dunstify -i $HOME/.icons/notif/phone.svg "Phone unmounted!" "~/phone"
;;
'Quit')
    echo "Programm Terminated." && exit 0
;;
esac
