#!/usr/bin/env bash
set -euo pipefail
source .config/dmscripts/config/config

# Drive to ignore (seperated with |)
IGNORED="sda|nvme"
 
DEVICE=$(lsblk -lp | grep "part" | grep -Ev "$IGNORED" | sort | ${DMENU} 'Choose drive:' | awk '{print $1}')

mount_usb() {
# Check if LUKS encrypted
if cryptsetup isLuks "$DEVICE" 2>/dev/null; then
    MOUNTPOINT="~/mnt/cusb"
    mkdir -p "$MOUNTPOINT"
    sudo cryptsetup open "$DEVICE" cusb
    sudo mount /dev/mapper/cusb "$MOUNTPOINT"
    echo "Mounted encrypted drive at $MOUNTPOINT"
else
    udisksctl mount -b "$DEVICE"
    dunstify -i $HOME/.icons/notif/drive.svg "Mounted drive" "$DEVICE"
fi
}

unmount_usb() {
# Check if LUKS encrypted
if cryptsetup isLuks "$DEVICE" 2>/dev/null; then
    MOUNTPOINT="~/mnt/cusb"
    mkdir -p "$MOUNTPOINT"
    sudo cryptsetup open "$DEVICE" cusb
    sudo mount /dev/mapper/cusb "$MOUNTPOINT"
    echo "Mounted encrypted drive at $MOUNTPOINT"
else
    udisksctl unmount -b "$DEVICE"
    dunstify -i $HOME/.icons/notif/drive.svg "Unmounted drive" "$DEVICE"
fi
}

choice=$(printf 'Mount USB\nUnmount USB\nMount Phone\nUnmount Phone\nQuit' | ${DMENU} 'USB:')
case "$choice" in
'Mount USB')
    mount_usb
;;
'Unmount USB')
    unmount_usb
;;
'Mount Phone')
    mkdir -p ~/phone
    jmtpfs ~/phone
;;
'Unmount Phone')
    fusermount -u ~/phone
;;
'Quit')
    echo "Programm Terminated." && exit 0
;;
esac
