#!/usr/bin/env bash
set -euo pipefail
source .config/dmscripts/config/config


choice=$(printf 'Alger\nParis\nBerlin\nBrussels' | ${DMENU} 'Get weather:' "$@")
choice="$(echo $choice | sed "s/ /-/g")"

if [ "$choice" ]; then
    day=$(printf 'Today\nTomorrow\nOvermorrow' | $DMENU 'Enter your query:') || exit
    case "${day}" in
        'Today')
    url="https://wttr.in/${choice}?m1&lang=de"
        ;;
        'Tomorrow')
    url="https://wttr.in/${choice}?m2&lang=de"
        ;;
        'Overmorrow')
    url="https://wttr.in/${choice}?m3&lang=de"
        ;;
    esac
    ./.local/bin/stay "curl -s '$url' | awk '!/Suivez/ && !/Emplacement/' | sed '1,7 s/^/                                             /' | sed 's/^/     /' | head -n -3 "
else
    echo "Program terminated." && exit 0
fi
