general.import = ["~/.config/alacritty/themes/tokyo-night.toml",]

[window]
opacity = 1.0
title = "Alacritty"

[window.padding]
x = 5 
y = 5 

[window.class]
instance = "Alacritty"
general =  "Alacritty"

[scrolling]
history = 5000
multiplier = 3

[font]
size= 12

[font.normal]
family= "Ubuntu Mono"
style  = "Regular"

[font.bold]
family= "Ubuntu Mono"
style = "Bold"

[font.italic]
family= "Ubuntu Mono"
style = "Italic"

[font.bold_italic]
family= "Ubuntu Mono"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"
